- name: set repo file
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
- name: install the latest version of Nginx
  yum:
    name: nginx
    state: latest
- name: start Nginx
  command: nginx
