version: 2

jobs:
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          command: terraform init
      - run:
          command: terraform plan
  deploy:
    docker:
      - image: chaspy/nginx-up-and-running
    steps:
      - checkout
      - run:
          command: | 
            echo "[web]\n$localhost" > hosts
            echo "\$nginx_ip=\"localhost"\" > spec/spec_hosts.rb
      - run:
          command: |
            ansible-playbook -i localhost ci.yml
            bundle exec rspec
workflows:
  version: 2
  plan_and_deploy:
    jobs:
      - plan
      - deploy
