version: 2

jobs:
  plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          command: terraform init
      - run:
          command: terraform plan

workflows:
  version: 2
  deploy:
    jobs:
      - plan
